
nginxApp:
  replicas: 15
  deploymentName: nginx-app
  containerName: nginx
  image:
    repository:  us-central1-docker.pkg.dev/master-tangent-417822/app-chart/docker-image
    tag: "v2"
  containerPortName: http
  containerPortNumber: 80
  containerTargetPortNumber: 80

serviceAccountName: nginx-service-account

serviceName: nginx-svc