apiVersion: apps/v1
kind: Deployment
metadata: 
  name: nginx-app
  labels:
    managed-by: dso 
spec:
  replicas: {{ .Values.replicas}}
  selector:
    matchLabels:
      application: nginx-app
  template:
    metadata:
      labels:
        application: nginx-app
    spec:
      serviceAccountName: {{ .Values.serviceAccountName}} #nginx-sa
      containers:
        - name: {{ .Values.containerName}} #nginx
          image: {{ .Values.image.repository}}:{{ .Values.image.tag}} #us-central1-docker.pkg.dev/master-tangent-417822/app-chart/docker-image:v5
          ports:
            - name: {{ .Values.containerPortName}} #http
              containerPort: {{ .Values.containerPortNumber}}  #80
