
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.serviceName }}
  labels:
{{- include "commonLabels" . | nindent 4 }}
spec:
  selector:
    application: nginx-app
  ports:
    - name: {{ .Values.nginxApp.containerPortName }}
      port: {{ .Values.nginxApp.containerPortNumber }}
      targetPort: {{ .Values.nginxApp.targetPortNumber }}
      