# apiVersion: v1
# kind: ServiceAccount
# metadata:
#   name: nginx-sa
#   labels:
#     managed-by: dso
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccountName }}
  labels:
{{- include "commonLabels" . | nindent 4 }}

